WebMVC_PT/Controllers/FullContractController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;

namespace WebMVC_PT.Controllers
{
    public class FullContractController : Controller
    {
        QUANLYBDS_TEAM3Entities data = new QUANLYBDS_TEAM3Entities();
        // GET: FullContract
        public ActionResult Index(string strSearch, int? i)
        {
            List<Full_Contract> listtemp = data.Full_Contract.ToList();
 
        
            return View(data.Full_Contract.OrderByDescending(s => s.Full_Contract_Code).Where(x=>x.Full_Contract_Code.StartsWith(strSearch) || strSearch==null).ToList().ToPagedList(i ?? 1, 5));
        }
        public ActionResult Create() 
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Full_Contract FCt) 
        {
            data.Full_Contract.Add(FCt);
            data.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Edit (int ID)
        {
            Full_Contract FCt= data.Full_Contract.Find(ID);
            return View(FCt);
        }
        [HttpPost]
        public ActionResult Edit(Full_Contract FCt)
        {
            Full_Contract Fc = data.Full_Contract.Find(FCt.ID);
            Fc.Full_Contract_Code = FCt.Full_Contract_Code;
            Fc.Customer_Name = FCt.Customer_Name;
            Fc.Year_Of_Birth = FCt.Year_Of_Birth;
            Fc.SSN = FCt.SSN;
            Fc.Customer_Address = FCt.Customer_Address;
            Fc.Mobile = FCt.Mobile;
            Fc.Property_ID = FCt.Property_ID;
            Fc.Date_Of_Contract = FCt.Date_Of_Contract;
            Fc.Price = FCt.Price;
            Fc.Deposit = FCt.Deposit;
            Fc.Remain = FCt.Remain;
            Fc.Status = FCt.Status;
            data.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details (int ID)
        {
            Full_Contract FCt = data.Full_Contract.Find(ID);
            return View(FCt);
        }
        public ActionResult Delete(int? ID)
        {
            Full_Contract FCt = data.Full_Contract.Find(ID);
            return View(FCt);
        }
        [HttpPost]
        public ActionResult Delete(int ID)
        {
            Full_Contract FCt = data.Full_Contract.Find(ID);
            data.Full_Contract.Remove(FCt);
            data.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

WebMVC_PT/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebMVC_PT.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebMVC_PT/Views/FullContract/Create.cshtml
@model WebMVC_PT.Full_Contract

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thêm mới hợp đồng</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Customer_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year_Of_Birth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year_Of_Birth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year_Of_Birth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SSN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SSN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SSN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer_Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer_Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer_Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Property_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Property_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Property_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Of_Contract, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Of_Contract, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_Of_Contract, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Deposit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Deposit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Deposit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remain, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remain, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remain, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-primary" />|
                @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebMVC_PT/Views/FullContract/Delete.cshtml
@model WebMVC_PT.Full_Contract

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Xóa hợp đồng</h2>

<h3>Bạn có chắc muốn xóa hợp đồng?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Full_Contract_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Full_Contract_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year_Of_Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year_Of_Birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SSN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SSN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Of_Contract)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Of_Contract)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deposit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deposit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-primary" })
        </div>
    }
</div>

WebMVC_PT/Views/FullContract/Details.cshtml
@model WebMVC_PT.Full_Contract

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Chi tiết hợp đồng</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Full_Contract_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Full_Contract_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year_Of_Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year_Of_Birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SSN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SSN)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer_Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Property_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Property_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Of_Contract)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Of_Contract)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deposit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deposit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Chỉnh sửa", "Edit", routeValues: new { id = Model.ID }, htmlAttributes: new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-primary" })

</p>

WebMVC_PT/Views/FullContract/Edit.cshtml
@model WebMVC_PT.Full_Contract

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Chỉnh sửa hợp đồng</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)
    <div class="form-group">
        @Html.LabelFor(model => model.Full_Contract_Code, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Full_Contract_Code, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Full_Contract_Code, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Customer_Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Customer_Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Customer_Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Year_Of_Birth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Year_Of_Birth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Year_Of_Birth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SSN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SSN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SSN, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Customer_Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Customer_Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Customer_Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Property_ID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Property_ID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Property_ID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date_Of_Contract, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date_Of_Contract, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date_Of_Contract, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Deposit, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Deposit, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Deposit, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Remain, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Remain, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Remain, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Status)
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div action="Index" class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-primary" /> |
            @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebMVC_PT/Views/FullContract/Index.cshtml
@model  IPagedList<WebMVC_PT.Full_Contract>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using PagedList.Mvc;
@using PagedList;

<h2>DANH SÁCH HỢP ĐỒNG</h2>

<p>
    @Html.ActionLink("Thêm hợp đồng", "Create", null, new { @class = "btn btn-primary" })
    @using (Html.BeginForm("Index", "FullContract", FormMethod.Get))
    {
        <div class="input-group">
            <div><input type="text" name="strSearch" class="form-control" placeholder="Nhập mã hợp đồng" /></div>
            <div><button type="submit" class="btn btn-primary" value="Search">Tìm kiếm</button></div>
        </div>
    }
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().Full_Contract_Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Customer_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Year_Of_Birth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().SSN)

        <th>
            @Html.DisplayNameFor(model => model.First().Customer_Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Mobile)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model.OrderByDescending(s=>s.Full_Contract_Code))
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Full_Contract_Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year_Of_Birth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SSN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer_Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mobile)
            </td>

            <td>
                @Html.ActionLink("Sửa", "Edit", routeValues: new { id = item.ID }, htmlAttributes: new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Chi tiết", "Details", routeValues: new { id = item.ID }, htmlAttributes: new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Xóa", "Delete", routeValues: new { id = item.ID }, htmlAttributes: new { @class = "btn btn-primary" })

            </td>
        </tr>
    }

</table>
@Html.PagedListPager(Model, i => Url.Action("Index", "FullContract", new { i, search = Request.QueryString["search"] }))

WebMVC_PT/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

WebMVC_PT/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

WebMVC_PT/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

WebMVC_PT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> SunShine Team</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-white bg-light">
        <div class="navbar-brand">
            <a class="navbar-brand" href="index.html"><img src="~/img/logo2.png" width="128" height="66" class="d-inline-block align-top" alt="additional title" /></a>
        </div>
        <div class="container">
            @Html.ActionLink("SUNSHINE", "Index", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a>@Html.ActionLink("Quản lý Hợp đồng", "Index", "FullContract", new { area = "" }, new { @class = "nav-link" })</a>
                    </li>
                    <li class="nav-item">
                        <a>@Html.ActionLink("Thêm mới hợp đồng", "Create", "FullContract", new { area = "" }, new { @class = "nav-link" })</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />

        <footer>
            <p>&copy;Copyright by Team SunShine</p>
        </footer>
    </div>
    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>